apiVersion: v2
name: cluster-api-provider-vsphere
version: 2.1.0
appVersion: v1.13.1
description: A Helm chart for cluster api provider vsphere
home: https://github.com/giantswarm/cluster-api-provider-vsphere-app
icon: https://s.giantswarm.io/app-icons/vsphere/2/icon-dark.png
sources:
  - https://github.com/giantswarm/cluster-api-provider-vsphere-app
annotations:
  application.giantswarm.io/team: "rocket"
  io.giantswarm.application.team: "rocket"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
